### PR TITLE
feat: introduce `posts sync` command

### LINKED ISSUE #2: Add sync command to create/update all posts at once

### LINKED ISSUE #5: Automatically add the slug on the markdown file on post creation

### PR DESCRIPTION
**Pull request by ratsclub**
## Motivation

This PR introduces the `posts sync` subcommand, the idea being a simple way to sync all your posts with the platform with a single command.

## Linked Issues/PRs/Discussions

#2

### CODE REVIEW

**Comment by ratsclub** [comment]
@sirodoht would you be able to test this? It would be awesome to receive an external feedback! 

If you need some help setting up Go, I could just compile the code and send a binary here. ~Perhaps setup a proper CI/CD environment on GitHub too.~

**Comment by sirodoht** [comment]
Of course! Looking now.

**Comment by ratsclub** [comment]
I just introduced the quality of life feature that updates the `slug` attribute when the post is created for the first time. I guess this should be here too, otherwise people will sync their markdown files and duplicate a lot of posts as they won't have any slugs on them.

**Comment by sirodoht** [comment]
@vtrf hmm, I'm getting this error:

```sh
$ mata posts list
2022/10/10 15:01:42 error build mataroa client: please, provide a non-empty token

$ tree .
.
└── posts
    ├── one.md
    └── two.md

1 directory, 2 files

$ mata posts sync posts/
2022/10/10 15:02:11 error build mataroa client: please, provide a non-empty token
```

What am I missing?

**Pull request closed without merging**
